package chung.crud.model;
// Generated Jul 28, 2020, 6:19:13 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users", schema = "public")
public class User implements java.io.Serializable {

	private String email;
	private String name;
	private String pass;
	private String intro;

	public User() {
	}

	public User(String email) {
		this.email = email;
	}

	public User(String email, String name, String pass, String intro) {
		this.email = email;
		this.name = name;
		this.pass = pass;
		this.intro = intro;
	}

	@Id

	@Column(name = "email", unique = true, nullable = false, length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "pass", length = 50)
	public String getPass() {
		return this.pass;
	}

	public void setPass(String pass) {
		this.pass = pass;
	}

	@Column(name = "intro", length = 250)
	public String getIntro() {
		return this.intro;
	}

	public void setIntro(String intro) {
		this.intro = intro;
	}

}
